name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        terraform-versions: [0.14.8, latest]
        go-versions: [1.16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix['terraform-versions'] }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix['go-versions'] }}

      - name: Run tests
        run: cd tests; go test -count 1 -timeout 0
