name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: tests/go.mod

      - name: Test
        run: go test -count 1 -timeout 0
        working-directory: tests
